import { NutrientTarget } from './types';

export const NUTRIENT_TARGETS: NutrientTarget[] = [
  { id: 'calories', name: 'Calories', unit: 'kcal', daily: 2000, category: 'macro' },
  { id: 'protein', name: 'Protein', unit: 'g', daily: 50, category: 'macro' },
  { id: 'totalFat', name: 'Total Fat', unit: 'g', daily: 65, category: 'macro' },
  { id: 'satFat', name: 'Saturated Fat', unit: 'g', daily: 20, category: 'macro' },
  { id: 'carbs', name: 'Carbohydrates', unit: 'g', daily: 300, category: 'macro' },
  { id: 'fiber', name: 'Fiber', unit: 'g', daily: 25, category: 'macro' },
  { id: 'sugar', name: 'Sugar', unit: 'g', daily: 50, category: 'macro' },
  { id: 'vitaminA', name: 'Vitamin A', unit: 'mcg', daily: 700, category: 'vitamin' },
  { id: 'vitaminC', name: 'Vitamin C', unit: 'mg', daily: 75, category: 'vitamin' },
  { id: 'vitaminD', name: 'Vitamin D', unit: 'mcg', daily: 15, category: 'vitamin' },
  { id: 'vitaminE', name: 'Vitamin E', unit: 'mg', daily: 15, category: 'vitamin' },
  { id: 'vitaminK1', name: 'Vitamin K1', unit: 'mcg', daily: 90, category: 'vitamin' },
  { id: 'vitaminK2', name: 'Vitamin K2 (MK-7)', unit: 'mcg', daily: 100, category: 'vitamin' },
  { id: 'thiamin', name: 'Thiamin (B1)', unit: 'mg', daily: 1.1, category: 'vitamin' },
  { id: 'riboflavin', name: 'Riboflavin (B2)', unit: 'mg', daily: 1.1, category: 'vitamin' },
  { id: 'niacin', name: 'Niacin (B3)', unit: 'mg', daily: 14, category: 'vitamin' },
  { id: 'vitaminB6', name: 'Vitamin B6', unit: 'mg', daily: 1.3, category: 'vitamin' },
  { id: 'folate', name: 'Folate (B9)', unit: 'mcg', daily: 400, category: 'vitamin' },
  { id: 'vitaminB12', name: 'Vitamin B12', unit: 'mcg', daily: 2.4, category: 'vitamin' },
  { id: 'calcium', name: 'Calcium', unit: 'mg', daily: 1000, category: 'mineral' },
  { id: 'iron', name: 'Iron', unit: 'mg', daily: 18, category: 'mineral' },
  { id: 'magnesium', name: 'Magnesium', unit: 'mg', daily: 320, category: 'mineral' },
  { id: 'phosphorus', name: 'Phosphorus', unit: 'mg', daily: 700, category: 'mineral' },
  { id: 'potassium', name: 'Potassium', unit: 'mg', daily: 2600, category: 'mineral' },
  { id: 'sodium', name: 'Sodium', unit: 'mg', daily: 2300, category: 'mineral' },
  { id: 'zinc', name: 'Zinc', unit: 'mg', daily: 8, category: 'mineral' },
  { id: 'selenium', name: 'Selenium', unit: 'mcg', daily: 55, category: 'mineral' },
];

export const USDA_NUTRIENT_MAP: Record<string, number> = {
  calories: 1008,
  protein: 1003,
  totalFat: 1004,
  carbs: 1005,
  fiber: 1079,
  sugar: 2000,
  calcium: 1087,
  iron: 1089,
  magnesium: 1090,
  phosphorus: 1091,
  potassium: 1092,
  sodium: 1093,
  zinc: 1095,
  vitaminA: 1106,
  vitaminC: 1162,
  vitaminD: 1114,
  vitaminE: 1109,
  vitaminK1: 1185,
  thiamin: 1165,
  riboflavin: 1166,
  niacin: 1167,
  vitaminB6: 1175,
  folate: 1177,
  vitaminB12: 1178,
  selenium: 1103,
};
